version: '3.6'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    command: mysqld --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_TCP_PORT: 3307
    ports:
      - ${MYSQL_PORT}:3307
    volumes:
      - ${VOLUME_DIR}/mysql:/var/lib/mysql

  mariadb:
    image: mariadb
    container_name: maria-db
    restart: always
    command: --plugin-load-add=auth_ed25519
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_TCP_PORT: 3308
    ports:
      - ${MARIADB_PORT}:3308
    volumes:
      - ${VOLUME_DIR}/mariadb:/var/lib/mysql

  postgres:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    container_name: postgres-db
    restart: always
    command: 
      -c ssl=on 
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${DB_ROOT_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /data/postgres
    ports:
      - ${PSQL_PORT}:5432
    volumes:
      - ${VOLUME_DIR}/postgres:/data/postgres

  redis:
    image: redis/redis-stack:6.2.6-v7
    container_name: redis-db
    restart: always
    environment:
      REDIS_ARGS: --requirepass password --user ${DB_USER} on >${DB_PASSWORD} ~* allcommands --user default on >${DB_ROOT_PASSWORD} ~* allcommands
      REDIS_PORT: 6379
      REDIS_TLS_ENABLED: "yes"
      REDIS_TLS_CERT_FILE: /usr/local/etc/redis/redis.crt
      REDIS_TLS_KEY_FILE: /usr/local/etc/redis/redis.key
      REDIS_TLS_CA_FILE: /usr/local/etc/redis/ca.crt
    ports:
    - ${REDIS_PORT}:6379
    volumes:
      - ${VOLUME_DIR}/redis:/data

  mongodb:
    image: mongo
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - ${VOLUME_DIR}/mongo:/data/db

  clickhouse:
    image: clickhouse/clickhouse-server:23.8.7.24-alpine
    container_name: clickhouse-db
    restart: always
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_USER: ${DB_USER}
      CLICKHOUSE_PASSWORD: ${DB_PASSWORD}
      CLICKHOUSE_DB: ${DB_DATABASE}
    ports:
      - ${CLICKHOUSE_HTTP}:8123
      - ${CLICKHOUSE_TCP}:9000
    volumes:
      - ${VOLUME_DIR}/clickhouse:/var/lib/clickhouse

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: mssql-db
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${DB_ROOT_PASSWORD}
      MSSQL_PID: Developer
    ports:
      - ${MSSQL_PORT}:1433
    volumes:
      - ${VOLUME_DIR}/mssql/data:/var/opt/mssql/data
      - ${VOLUME_DIR}/mssql/secrets:/var/opt/mssql/secrets

  oracle:
    image: gvenzl/oracle-free
    container_name: oracle-db
    restart: always
    environment:
      ORACLE_PASSWORD: ${DB_ROOT_PASSWORD}
      APP_USER: ${DB_USER}
      APP_USER_PASSWORD: ${DB_PASSWORD}
      ORACLE_DATABASE: ${DB_DATABASE}
    ports:
      - ${ORACLE_PORT}:1521